default: &default
adapter: postgresql
encoding: unicode
pool: 5
username: 'suraj'
password: 'jw8s0F4'
template: template0
host: localhost
development:
<<: *default
database: app_development
test:
<<: *default
database: app_test
production:
<<: *default
database: app_production